### ISSUE TITLE
Fastest lap

### ISSUE THREAD

**Issue by Crisjeeeee** [masterplane8/F1-League-Management#10]
Hi there, i  have a issue with the fastest lap that has been driven by a driver.
the driver got the fastest lap in a race but DNF, now the fastest lap goes to somebody else.
but IRL that isnt the way it works, is there a solution for this?

Greetz

**Comment by masterplane8** [comment]
@Crisjeeeee Thanks for pointing this out, it'll be fixed in the next release. I'm just waiting on details of another thing that may need to be fixed as well, but it'll be out soon.
