### ISSUE TITLE
Multiple lap-down drivers

### ISSUE THREAD

**Issue by LukeCarmona** [masterplane8/F1-League-Management#13]
Great product all-in-all, but I am curious about how to better manage lapped drivers.

Example:
Six drivers end up 1-lap down, so I insert "1 lap" for each of those 6 drivers.  The problem is that the spreadsheet does not know which order the six lapped drivers are in, therefore giving them all the same finishing position, which of course then leads to the points not updating on the scoring table, and so forth.  As a result, I currently must resort to using the intervals column to denote what position they finished in (with 1st being 0 of course).  I then have to hide the interval column in the race reports since it is not actually displaying intervals.

Is if there is a way to accurately order lapped cars so that the race reports show multiple drivers the same lap down?  I would like to display the interval column in the race reports, but not with inaccuracies, like listing six 1-lap down drivers as "1 lap" "2 laps" "3 laps", etc, when they are all 1-lap down.

**Comment by masterplane8** [comment]
At the top of the final classifications page is a table of instructions for how to enter in data in each column. For drivers who finish a number of laps down or DNF, the way to signify order is as follows: "1 Lap - 1" or "1 Lap - 2". The spaces between dashes are required. The driver who finishes first of the drivers 1 lap down would be given "1 Lap - 1".

**Comment by LukeCarmona** [comment]
I see, thank you for clarifying.  I was aware of the instructions at the top, but my brain was interpreting that particular section rather differently.
