### ISSUE TITLE
Another Feature update?

### ISSUE THREAD

**Issue by Isak302** [masterplane8/F1-League-Management#16]
Hi!

I also wanted to say great work you've done here! I didn't know where to ask you about another statistic that would be neat to have, so I'm asking you here.

It would be nice to have the amount of pit stops each driver does in a race. I think it would be cool to see after the season how many pit stops people did in total over a season, average pit stops per race and how many they did in a specific race.

Obviously this is just a small feature that I don't really know how to add and this sheet already have everything else I need.

**Comment by masterplane8** [comment]
For the sake of keeping the Final Classifications page as least intimidating as possible, I am not going to add any more data input columns for each race. If you think of a statistic that I can derive from the current data prompts, let me know.

**Comment by Isak302** [comment]
I understand the reasoning and I agree with keeping it simple.
One thing I could think of from the current data is a table with all drivers and all tracks and then their fastest lap shown for each track.

Thank you again for this. A lot of people are really enjoying the stastistic in my league!
