### ISSUE TITLE
Cell selecting

### ISSUE THREAD

**Issue by DangerDB1** [masterplane8/F1-League-Management#18]
Hey Masterplane. I absolutely love your sheet.
In previous versions I was able to select multiple cells and copy as image which I used to post on our discord.
Now I have to do a prt sc which lowers the quality of the picture drastically. Will it be possible to change it back to the way it was please?

Kind regards
Daniel
![image](https://user-images.githubusercontent.com/111731215/185860201-df914986-c3fc-476a-8ca1-daa447f07e7d.png)

**Comment by masterplane8** [comment]
To unlock the pages, go to the Review tool tab and select "Unprotect Sheet"
