### ISSUE TITLE
Add more than 24 tracks in the track list

### ISSUE THREAD

**Issue by jgallardo64** [masterplane8/F1-League-Management#6]
Hi!

First of all congrats on the sheet, it's very complete in everything, good job!

I was wondering if it would be possible to have more than 24 tracks in the track list to have more than 24 rounds in the championship.

Thanks!

**Comment by masterplane8** [comment]
Hey @jgallardo64,

Glad you like the sheet! How many races total would you like? I can expand the season length, but I'll only publish it publicly if its a reasonable size; somewhere around 30 tracks long or something like that. Otherwise I may end up sending it directly to you.

**Comment by jgallardo64** [comment]
Yeah @masterplane8, 30 tracks sound like a reasonable size for me! ;)

**Comment by jgallardo64** [comment]
Hello, @masterplane8. Any ETA on when will you release the new version? Thanks!

**Comment by masterplane8** [comment]
Either tonight (EST) or tomorrow. I found a few other things that needed to be fixed and I'm making some quality-of-life improvements too, so it's taking a little longer than I anticipated.

**Comment by jgallardo64** [comment]
Ok great to hear that, thanks mate! 👍

**Comment by masterplane8** [comment]
Little update. I decided to spend some time rewriting a lot of the back end parts of this sheet to make everything run smoother and make updating it easier in the long run. Updating it to 30 races was way more tedious than I thought it would be. That being said, it takes time. I expect I'll have it done in the next few days. Sorry for the delay, but I'd rather release something that I feel is well made, rather than thrown together.

**Comment by jgallardo64** [comment]
Yeah no worries, take your time and make it easier for you to update it in the future

**Comment by jgallardo64** [comment]
Hi @masterplane8, how is the update going?

**Comment by masterplane8** [comment]
So far so good. I have had very little time in the past week to work on it (finals week), hence the delay. Should be out by the end of this week or early next week.

**Comment by jgallardo64** [comment]
Great to hear. Sorry if im very annoying, just want to have my league finished with the last race hahaha.

Thanks @masterplane8!
