### ISSUE TITLE
Race results 

### ISSUE THREAD

**Issue by Feralelite** [masterplane8/F1-League-Management#8]
How do I put in the race result because it just says dnp

**Comment by Feralelite** [comment]
I have figured that out now but what does this mean 
![Uploading 7DC65741-DB64-41A6-BEBF-49D8CF7F9B19.jpeg…]()

**Comment by Feralelite** [comment]
![13BE1929-3AF7-47DC-8D25-665CC320EF9A](https://user-images.githubusercontent.com/96693678/147415990-5fb74c6a-015c-4fab-ab47-51a3ad786222.jpeg)

**Comment by Feralelite** [comment]
![Uploading D8BEA2A7-94EC-4D1D-A2F4-75ADD2D22AC7.jpeg…]()

**Comment by Feralelite** [comment]
![Uploading 33737657-5D10-4353-967F-F39F4DF7D76C.jpeg…]()

**Comment by masterplane8** [comment]
Hey @Feralelite,

Please take a look at this post to help fix your problem: https://github.com/masterplane8/F1-League-Management/issues/3#issue-1017144441
