### ISSUE TITLE
Customisation

### ISSUE THREAD

**Issue by AidanDev** [masterplane8/F1-League-Management#9]
Is it possible to change tracks that are available to a track that isn’t there like Nurburgring. And is it possible to change the team colours as well? 

I want to use this spreadsheet for a league in GT Sport

**Comment by masterplane8** [comment]
Hey @AidanDev, 

Changing the track list is something that I could Integrate. I would probably create another column on the League Management page that would ask you to enter a tracks three letter abbreviation for the Race and Qualifying Results tables, or I could just make a database of all the tracks in the most popular racing games and abbreviations for each one. I'll put some more thought into it.

For the team colors, it's a little tricky, and I'm not sure it'll be possible. All of the dynamic color changes are operated by Excels Conditional Formatting, which does not support user input changes very well. In other words, I can't make it automatically change to colors that a user asks it to change to. I'll look into it a little more and see what I can do
